[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_upload.flash_size = 8MB

lib_deps =
  heltec-aaron-lee/Heltec ESP32 Dev-Boards @ ^2.1.0
  Wire
  SPI
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM

monitor_speed = 115200
upload_speed = 921600

; Merged binary output for ESP Web Tools
extra_scripts = post:scripts/merge_firmware.py
